obj-y += lib/

obj-$(CONFIG_EARLY_PRINTK) += debug.o
obj-y += domctl.o
obj-y += domain.o
obj-y += entry.o
obj-y += head.o
obj-y += insn.o
obj-$(CONFIG_LIVEPATCH) += livepatch.o
obj-y += proc-v7.o proc-caxx.o
obj-$(CONFIG_AARCH32_V8R) += proc-v8.o
obj-y += smpboot.o
obj-y += traps.o
obj-y += vfp.o
obj-$(CONFIG_AARCH32_V8R) += mpu_v8r.o
